/**
  ******************************************************************************
  * @file           : aip31068l.c
  * @brief          : AiP31068L I2C-native LCD controller driver
  ******************************************************************************
  * SPDX-License-Identifier: MIT
  * Copyright (C) 2026 Stric Roberts.
  *
  * Permission is hereby granted, free of charge, to any person obtaining a
  * copy of this software and associated documentation files (the "Software"),
  * to deal in the Software without restriction, including without limitation
  * the rights to use, copy, modify, merge, publish, distribute, sublicense,
  * and/or sell copies of the Software, and to permit persons to whom the
  * Software is furnished to do so, subject to the following conditions:
  *
  * The above copyright notice and this permission notice shall be included in
  * all copies or substantial portions of the Software.
  *
  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  * IN THE SOFTWARE.
  *
  * SDK dependencies:
  *   sl_i2cspm.h           Silicon Labs I2CSPM polled master driver
  *   em_i2c.h              EMLIB I2C peripheral driver
  *   sl_i2cspm_instances.h Autogenerated instance handle (sl_i2cspm_pcf8574)
  *   Gecko SDK 4.4.5, i2cspm instance name: pcf8574
  *
  * Protocol reference: DFRobot_RGBLCD1602 C++ driver (MIT), yangfeng@dfrobot.com
  * AiP31068L control byte encoding:
  *   0x80 = Co=1, RS=0  →  command register
  *   0x40 = Co=0, RS=1  →  data register (stream mode)
  ******************************************************************************
  */

#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include "aip31068l.h"
#include "delay.h"
#include "sl_i2cspm.h"
#include "em_i2c.h"
#include "sl_i2cspm_instances.h"

/* Maps the autogenerated handle to a stable name.
 * Update only this line if the i2cspm instance is renamed in .slcp. */
#define aip31068l_i2c  sl_i2cspm_pcf8574

/* AiP31068L control byte values */
#define CTRL_CMD   0x80u   /* Co=1, RS=0 — command register */
#define CTRL_DATA  0x40u   /* Co=0, RS=1 — data register (stream) */

/* HD44780-compatible instruction bytes */
#define CMD_CLEAR         0x01u
#define CMD_RETURN_HOME   0x02u
#define CMD_ENTRY_MODE    0x06u   /* cursor right, no display shift */
#define CMD_DISPLAY_ON    0x0Cu   /* display on, cursor off, blink off */
#define CMD_FUNC_SET      0x28u   /* N=1 2-line, F=0 5x8 (DL ignored on I2C) */
#define CMD_SET_CGRAM     0x40u   /* OR with (slot << 3) */
#define CMD_SET_DDRAM     0x80u   /* OR with address */

#define DDRAM_ROW0  0x00u
#define DDRAM_ROW1  0x40u

/* ---------------------------------------------------------------------------
 * Internal helpers
 * ---------------------------------------------------------------------------*/

static void i2c_write(uint8_t addr, uint8_t const *p_data, uint8_t len)
{
    I2C_TransferSeq_TypeDef seq;

    seq.addr        = (uint16_t)(addr << 1u);
    seq.flags       = I2C_FLAG_WRITE;
    seq.buf[0].data = (uint8_t *)p_data;
    seq.buf[0].len  = len;

    (void)I2CSPM_Transfer(aip31068l_i2c, &seq);
}

static void send_command(uint8_t addr, uint8_t cmd)
{
    uint8_t buf[2] = { CTRL_CMD, cmd };
    i2c_write(addr, buf, 2u);
    delay_ms(1u);
}

static void send_data(uint8_t addr, uint8_t data)
{
    uint8_t buf[2] = { CTRL_DATA, data };
    i2c_write(addr, buf, 2u);
}

/* ---------------------------------------------------------------------------
 * Public API
 * ---------------------------------------------------------------------------*/

int aip31068l_init(uint8_t addr)
{
    delay_ms(50u);   /* VDD stabilise — datasheet requires > 40 ms */

    send_command(addr, CMD_FUNC_SET);
    delay_ms(5u);

    send_command(addr, CMD_FUNC_SET);
    delay_ms(5u);

    send_command(addr, CMD_FUNC_SET);

    send_command(addr, CMD_DISPLAY_ON);
    send_command(addr, CMD_CLEAR);
    delay_ms(2u);    /* Clear requires up to 1.53 ms */
    send_command(addr, CMD_ENTRY_MODE);

    return 0;
}

void aip31068l_command(uint8_t addr, uint8_t cmd)
{
    send_command(addr, cmd);
}

void aip31068l_clear(uint8_t addr)
{
    send_command(addr, CMD_CLEAR);
    delay_ms(2u);
}

void aip31068l_return_home(uint8_t addr)
{
    send_command(addr, CMD_RETURN_HOME);
    delay_ms(2u);
}

int aip31068l_set_cursor(uint8_t addr, uint8_t col, uint8_t row)
{
    uint8_t ddram_addr;
    bool b_valid;

    b_valid = (col < AIP31068L_COLS) && (row < AIP31068L_ROWS);

    if (b_valid)
    {
        ddram_addr = (0u == row)
                     ? (uint8_t)(DDRAM_ROW0 + col)
                     : (uint8_t)(DDRAM_ROW1 + col);

        send_command(addr, CMD_SET_DDRAM | ddram_addr);
    }

    return b_valid ? 0 : -1;
}

void aip31068l_write_char(uint8_t addr, char c)
{
    send_data(addr, (uint8_t)c);
}

void aip31068l_write_string(uint8_t addr, char const *p_str)
{
    assert(NULL != p_str);

    if (NULL != p_str)
    {
        while ('\0' != *p_str)
        {
            send_data(addr, (uint8_t)*p_str);
            p_str++;
        }
    }
}

void aip31068l_load_custom_char(uint8_t addr, uint8_t slot, uint8_t const *p_rows)
{
    uint8_t buf[AIP31068L_CGRAM_ROWS + 1u];
    uint8_t i;

    assert(NULL != p_rows);
    assert(slot < AIP31068L_CGRAM_SLOTS);

    if ((NULL == p_rows) || (slot >= AIP31068L_CGRAM_SLOTS))
    {
        return;
    }

    send_command(addr, CMD_SET_CGRAM | (uint8_t)((slot & 0x07u) << 3u));

    /* Stream all 8 pixel rows in one I2C transaction */
    buf[0] = CTRL_DATA;
    for (i = 0u; i < AIP31068L_CGRAM_ROWS; i++)
    {
        buf[i + 1u] = p_rows[i] & 0x1Fu;   /* mask to 5 bits */
    }

    i2c_write(addr, buf, (uint8_t)(AIP31068L_CGRAM_ROWS + 1u));
}
