/**
  ******************************************************************************
  * @file           : lcd_intfc.c
  * @brief          : Gecko SDK I2C implementation of the lcd_intfc interface
  ******************************************************************************
  * SPDX-License-Identifier: MIT
  * Copyright (C) 2026 Stric Roberts.
  *
  * Permission is hereby granted, free of charge, to any person obtaining a
  * copy of this software and associated documentation files (the "Software"),
  * to deal in the Software without restriction, including without limitation
  * the rights to use, copy, modify, merge, publish, distribute, sublicense,
  * and/or sell copies of the Software, and to permit persons to whom the
  * Software is furnished to do so, subject to the following conditions:
  *
  * The above copyright notice and this permission notice shall be included in
  * all copies or substantial portions of the Software.
  *
  * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  * IN THE SOFTWARE.
  *
  * SDK dependencies:
  *   sl_i2cspm.h           Silicon Labs I2CSPM polled master driver
  *   em_i2c.h              EMLIB I2C peripheral driver
  *   sl_i2cspm_instances.h Autogenerated instance handle (sl_i2cspm_lcd1602)
  *   Gecko SDK 4.4.5, i2cspm instance name: lcd1602
  *
  * To target a different I2C instance, update the sl_i2cspm_lcd1602 reference
  * below to the appropriate autogenerated handle name.
  ******************************************************************************
  */

#include "lcd_intfc.h"
#include "sl_i2cspm.h"
#include "em_i2c.h"
#include "em_cmu.h"
#include "sl_i2cspm_instances.h"

void lcd_intfc_init(void)
{
    sl_i2cspm_init_instances();
}

void lcd_intfc_bringup(void)
{
    sl_i2cspm_init_instances();
}

void lcd_intfc_teardown(void)
{
    I2C_Reset(sl_i2cspm_lcd1602);
    CMU_ClockEnable(cmuClock_I2C0, false);
}

lcd_intfc_status_t lcd_intfc_write(uint16_t addr, const uint8_t *data, size_t len)
{
    I2C_TransferSeq_TypeDef seq;

    seq.addr        = (uint16_t)(addr << 1u);
    seq.flags       = I2C_FLAG_WRITE;
    seq.buf[0].data = (uint8_t *)data;
    seq.buf[0].len  = (uint16_t)len;

    return (I2CSPM_Transfer(sl_i2cspm_lcd1602, &seq) == i2cTransferDone)
               ? LCD_INTFC_OK : LCD_INTFC_ERROR;
}
